name: Style

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
        override: true
    - name: Run rustfmt
      run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true
    - name: clippy
      run: cargo clippy --all
